import type {
  MarketplaceCategory,
  MarketplaceProduct,
  MerchantPromotion,
  MerchantReview,
  MerchantStore,
} from '@Types/marketplaceTypes';
import {MERCHANT_STORE_ID} from '@Types/marketplaceTypes';

export const MARKETPLACE_CATEGORIES: MarketplaceCategory[] = [
  {id: 'food', nameKey: 'marketplace.categories.food', icon: '🍔', color: '#F97316'},
  {id: 'grocery', nameKey: 'marketplace.categories.grocery', icon: '🛒', color: '#22C55E'},
  {id: 'pharmacy', nameKey: 'marketplace.categories.pharmacy', icon: '💊', color: '#3B82F6'},
  {id: 'electronics', nameKey: 'marketplace.categories.electronics', icon: '📱', color: '#8B5CF6'},
  {id: 'fashion', nameKey: 'marketplace.categories.fashion', icon: '👕', color: '#EC4899'},
  {id: 'home', nameKey: 'marketplace.categories.home', icon: '🏠', color: '#14B8A6'},
  {id: 'beauty', nameKey: 'marketplace.categories.beauty', icon: '💄', color: '#F472B6'},
  {id: 'pets', nameKey: 'marketplace.categories.pets', icon: '🐾', color: '#A16207'},
];

const withDefaults = (product: Omit<MarketplaceProduct, 'isEnabled'> & {isEnabled?: boolean}): MarketplaceProduct => ({
  ...product,
  isEnabled: product.isEnabled ?? true,
});

export const SEED_MERCHANT_STORE: MerchantStore = {
  id: MERCHANT_STORE_ID,
  name: 'RNTS Demo Store',
  description: 'Your Talabat-style merchant storefront for food, grocery, and more.',
  isOpen: true,
  rating: 4.8,
  reviewCount: 124,
  revenue: 2840.5,
  fulfilledOrders: 86,
};

export const SEED_MERCHANT_PRODUCTS: MarketplaceProduct[] = [
  withDefaults({
    id: 'mprod-1',
    categoryId: 'food',
    title: 'Chicken Shawarma Wrap',
    description: 'Garlic sauce, pickles, fries — bestseller.',
    price: 22,
    currency: 'AED',
    imageEmoji: '🌯',
    sellerName: SEED_MERCHANT_STORE.name,
    rating: 4.9,
    reviewCount: 48,
    stock: 4,
    merchantId: MERCHANT_STORE_ID,
    isOwnListing: true,
    isEnabled: true,
  }),
  withDefaults({
    id: 'mprod-2',
    categoryId: 'grocery',
    title: 'Family Breakfast Box',
    description: 'Eggs, bread, labneh, and fresh juice.',
    price: 45,
    currency: 'AED',
    imageEmoji: '🥐',
    sellerName: SEED_MERCHANT_STORE.name,
    rating: 4.7,
    reviewCount: 22,
    stock: 0,
    merchantId: MERCHANT_STORE_ID,
    isOwnListing: true,
    isEnabled: true,
  }),
];

export const SEED_MERCHANT_PROMOTIONS: MerchantPromotion[] = [
  {
    id: 'promo-1',
    title: '20% off Shawarma',
    description: 'Limited lunch offer on Chicken Shawarma Wrap.',
    type: 'percentage',
    value: 20,
    productIds: ['mprod-1'],
    isActive: true,
    startsAt: '2026-06-01T00:00:00Z',
    endsAt: '2026-12-31T23:59:59Z',
  },
  {
    id: 'promo-2',
    title: 'AED 10 off orders 50+',
    description: 'Store-wide minimum order discount.',
    type: 'fixed',
    value: 10,
    productIds: [],
    minOrderAmount: 50,
    isActive: false,
    startsAt: '2026-06-01T00:00:00Z',
    endsAt: '2026-12-31T23:59:59Z',
  },
];

export const SEED_MERCHANT_REVIEWS: MerchantReview[] = [
  {
    id: 'rev-1',
    customerName: 'Sara A.',
    rating: 5,
    comment: 'Shawarma was fresh and arrived hot. Will order again!',
    productTitle: 'Chicken Shawarma Wrap',
    createdAt: '2026-06-10T18:30:00Z',
    isRead: false,
  },
  {
    id: 'rev-2',
    customerName: 'Omar K.',
    rating: 4,
    comment: 'Good portions, delivery was a few minutes late.',
    productTitle: 'Family Breakfast Box',
    createdAt: '2026-06-08T09:15:00Z',
    merchantReply: 'Thanks Omar — we are improving delivery times!',
    isRead: true,
  },
  {
    id: 'rev-3',
    customerName: 'Lina M.',
    rating: 5,
    comment: 'Best shawarma in the area.',
    productTitle: 'Chicken Shawarma Wrap',
    createdAt: '2026-06-05T13:00:00Z',
    isRead: true,
  },
];

export const SEED_MARKETPLACE_PRODUCTS: MarketplaceProduct[] = [
  withDefaults({
    id: 'prod-1',
    categoryId: 'food',
    title: 'Mixed Grill Platter',
    description: 'Charcoal grilled chicken, kofta, and lamb with rice and salad.',
    price: 45,
    currency: 'AED',
    imageEmoji: '🍖',
    sellerName: 'Levant Kitchen',
    rating: 4.7,
    reviewCount: 328,
    stock: 50,
  }),
  withDefaults({
    id: 'prod-2',
    categoryId: 'food',
    title: 'Margherita Pizza',
    description: 'Stone-baked pizza with fresh mozzarella and basil.',
    price: 38,
    currency: 'AED',
    imageEmoji: '🍕',
    sellerName: 'Pizza Hub',
    rating: 4.5,
    reviewCount: 512,
    stock: 30,
  }),
  withDefaults({
    id: 'prod-3',
    categoryId: 'grocery',
    title: 'Fresh Fruit Box',
    description: 'Seasonal mixed fruits — apple, orange, banana, grapes.',
    price: 29,
    currency: 'AED',
    imageEmoji: '🍎',
    sellerName: 'Green Mart',
    rating: 4.6,
    reviewCount: 89,
    stock: 100,
  }),
  withDefaults({
    id: 'prod-4',
    categoryId: 'grocery',
    title: 'Organic Milk 1L',
    description: 'Farm fresh full-fat organic milk.',
    price: 8.5,
    currency: 'AED',
    imageEmoji: '🥛',
    sellerName: 'Green Mart',
    rating: 4.4,
    reviewCount: 201,
    stock: 200,
  }),
  withDefaults({
    id: 'prod-5',
    categoryId: 'pharmacy',
    title: 'Vitamin C Pack',
    description: '30 effervescent tablets, immune support.',
    price: 22,
    currency: 'AED',
    imageEmoji: '💊',
    sellerName: 'Care Pharmacy',
    rating: 4.8,
    reviewCount: 64,
    stock: 40,
  }),
  withDefaults({
    id: 'prod-6',
    categoryId: 'electronics',
    title: 'Wireless Earbuds',
    description: 'Noise cancelling, 24h battery, USB-C case.',
    price: 199,
    currency: 'AED',
    imageEmoji: '🎧',
    sellerName: 'Tech Zone',
    rating: 4.3,
    reviewCount: 156,
    stock: 15,
  }),
  withDefaults({
    id: 'prod-7',
    categoryId: 'fashion',
    title: 'Cotton T-Shirt',
    description: 'Premium cotton, unisex, multiple colors.',
    price: 59,
    currency: 'AED',
    imageEmoji: '👕',
    sellerName: 'Urban Wear',
    rating: 4.2,
    reviewCount: 44,
    stock: 25,
  }),
  withDefaults({
    id: 'prod-8',
    categoryId: 'home',
    title: 'Scented Candle Set',
    description: 'Set of 3 soy candles — lavender, vanilla, citrus.',
    price: 75,
    currency: 'AED',
    imageEmoji: '🕯️',
    sellerName: 'Home Comfort',
    rating: 4.9,
    reviewCount: 92,
    stock: 18,
  }),
  ...SEED_MERCHANT_PRODUCTS,
];

export const MARKETPLACE_DELIVERY_FEE = 7.5;
