import type {ThemeTokens} from '@theme/types';

/** Styles for the Madinah-inspired mushaf page chrome. */
export const resolveMushafPageSheetStyles = (tokens: ThemeTokens) => ({
  outerFrame: {
    flex: tokens.layout.flex.fill,
    marginHorizontal: tokens.spacing.sm,
    marginBottom: tokens.spacing.sm,
    borderRadius: tokens.radius.md,
    borderWidth: tokens.layout.borderWidth.lg,
    borderColor: tokens.colors.mushafBorderOuter,
    backgroundColor: tokens.colors.mushafBorderOuter,
    padding: tokens.spacing.xxs,
    ...tokens.shadows.md,
  },
  midFrame: {
    flex: tokens.layout.flex.fill,
    borderRadius: tokens.radius.sm,
    borderWidth: tokens.layout.borderWidth.md,
    borderColor: tokens.colors.mushafOrnament,
    backgroundColor: tokens.colors.mushafBanner,
    padding: tokens.spacing.xxs,
  },
  innerFrame: {
    flex: tokens.layout.flex.fill,
    borderRadius: tokens.radius.sm,
    borderWidth: tokens.layout.borderWidth.sm,
    borderColor: tokens.colors.mushafBorder,
    backgroundColor: tokens.colors.mushafPage,
    overflow: 'hidden' as const,
  },
  header: {
    ...tokens.layout.presets.rowBetween,
    alignItems: 'center' as const,
    paddingHorizontal: tokens.spacing.sm,
    paddingVertical: tokens.spacing.xs,
    borderBottomWidth: tokens.layout.borderWidth.sm,
    borderBottomColor: tokens.colors.mushafBorder,
    backgroundColor: tokens.colors.mushafBanner,
    gap: tokens.spacing.xs,
  },
  headerText: {
    flex: tokens.layout.flex.fill,
    color: tokens.colors.mushafMeta,
    fontSize: tokens.typography.caption.fontSize,
    lineHeight: tokens.typography.caption.lineHeight,
    fontWeight: '600' as const,
    writingDirection: 'rtl' as const,
  },
  headerJuz: {
    color: tokens.colors.mushafMeta,
    fontSize: tokens.typography.caption.fontSize,
    lineHeight: tokens.typography.caption.lineHeight,
    fontWeight: '700' as const,
    writingDirection: 'rtl' as const,
  },
  body: {
    flexGrow: 1,
    paddingHorizontal: tokens.spacing.md,
    paddingVertical: tokens.spacing.md,
    justifyContent: 'center' as const,
  },
  segment: {
    marginBottom: tokens.spacing.md,
  },
  surahBanner: {
    alignSelf: 'stretch' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    marginBottom: tokens.spacing.sm,
    paddingVertical: tokens.spacing.sm,
    paddingHorizontal: tokens.spacing.md,
    borderRadius: tokens.radius.sm,
    borderWidth: tokens.layout.borderWidth.md,
    borderColor: tokens.colors.mushafBorderOuter,
    backgroundColor: tokens.colors.mushafBanner,
  },
  surahBannerText: {
    color: tokens.colors.mushafInk,
    fontSize: tokens.typography.h3.fontSize,
    lineHeight: tokens.typography.h3.lineHeight,
    fontWeight: '700' as const,
    textAlign: 'center' as const,
    writingDirection: 'rtl' as const,
  },
  basmala: {
    ...tokens.typography.mushafBasmala,
    color: tokens.colors.mushafInk,
    textAlign: 'center' as const,
    writingDirection: 'rtl' as const,
    marginBottom: tokens.spacing.sm,
  },
  ayahFlow: {
    ...tokens.typography.mushafBody,
    textAlign: 'center' as const,
    writingDirection: 'rtl' as const,
    color: tokens.colors.mushafInk,
  },
  ayahActive: {
    backgroundColor: tokens.colors.mushafHighlight,
    borderRadius: tokens.radius.sm,
  },
  ayahMarker: {
    ...tokens.typography.mushafMarker,
    color: tokens.colors.mushafOrnament,
  },
  footer: {
    alignItems: 'center' as const,
    paddingVertical: tokens.spacing.sm,
    borderTopWidth: tokens.layout.borderWidth.sm,
    borderTopColor: tokens.colors.mushafBorder,
    backgroundColor: tokens.colors.mushafBanner,
  },
  pageBadge: {
    minWidth: tokens.sizes.touchTarget * 0.7,
    paddingHorizontal: tokens.spacing.md,
    paddingVertical: tokens.spacing.xxs,
    borderRadius: tokens.radius.full,
    borderWidth: tokens.layout.borderWidth.md,
    borderColor: tokens.colors.mushafBorderOuter,
    backgroundColor: tokens.colors.mushafPage,
    alignItems: 'center' as const,
  },
  pageBadgeText: {
    color: tokens.colors.mushafMeta,
    fontSize: tokens.typography.caption.fontSize,
    fontWeight: '700' as const,
    writingDirection: 'rtl' as const,
  },
  corner: {
    position: 'absolute' as const,
    width: tokens.spacing.lg,
    height: tokens.spacing.lg,
    zIndex: tokens.layout.zIndex.raised,
  },
  cornerTopStart: {
    top: tokens.spacing.xxs,
    start: tokens.spacing.xxs,
  },
  cornerTopEnd: {
    top: tokens.spacing.xxs,
    end: tokens.spacing.xxs,
  },
  cornerBottomStart: {
    bottom: tokens.spacing.xxs,
    start: tokens.spacing.xxs,
  },
  cornerBottomEnd: {
    bottom: tokens.spacing.xxs,
    end: tokens.spacing.xxs,
  },
});
